clear all;
triton_orbit(1,1);
uicontrol('Style', 'popup',...
           'String', 'Away from Sun, Above Axis|Away from Sun, Below Axis|Towards Sun, Above Axis|Towards Sun, Below Axis',...
           'Position', [20 340 100 50],...
           'Callback', @change3d);